package viewSwing;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.ExercisesStatus;
import model.Progress;
import model.Schedule;
import reponsitory.ProgressRepository;
import service.ProgressService;
import service.ScheduleService;
import service.UserService;
import view.View;
import static view.View.DATE_FORMAT;

/**
 *
 * @author RAVEN
 */
public class CoachTranning extends javax.swing.JFrame {

    private Login login;
    private List<Progress> progresses;
    private ProgressService progressService;

    public CoachTranning() {
        initComponents();
        setResizable(false);
        progresses = new ProgressRepository().readFile();
        progressService = new ProgressService();
        login = new Login();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        viewTE = new javax.swing.JTextField();
        viewCE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        viewBMI = new javax.swing.JTextField();
        liquidProgress = new progressSwing.LiquidProgress();
        jLabel1 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnAdvide = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        viewDate = new javax.swing.JTextField();
        viewEX1 = new javax.swing.JTextField();
        viewEX2 = new javax.swing.JTextField();
        jStatusEX1 = new javax.swing.JRadioButton();
        jStatusEX2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnTrain = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtAdvide = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        viewName = new javax.swing.JTextField();
        viewLevel = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        viewphonr = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lotus.png"))); // NOI18N

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/treadmill.png"))); // NOI18N

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ta.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tranning.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel3.setText("Total Exercises");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel5.setText("Completed Exercises");

        viewTE.setEditable(false);
        viewTE.setBackground(new java.awt.Color(255, 255, 255));

        viewCE.setEditable(false);
        viewCE.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel7.setText("Current BMI");

        viewBMI.setEditable(false);
        viewBMI.setBackground(new java.awt.Color(255, 255, 255));
        viewBMI.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        viewBMI.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        liquidProgress.setBackground(new java.awt.Color(153, 219, 255));
        liquidProgress.setForeground(new java.awt.Color(42, 161, 233));
        liquidProgress.setValue(40);
        liquidProgress.setAnimateColor(new java.awt.Color(255, 255, 255));
        liquidProgress.setBorderColor(new java.awt.Color(42, 161, 233));
        liquidProgress.setBorderSize(8);
        liquidProgress.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        liquidProgress.setSpaceSize(10);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kcal.png"))); // NOI18N
        jLabel1.setText("USER PROGRESS");

        btnView.setBackground(new java.awt.Color(255, 153, 153));
        btnView.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 102, 102));
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calories.png"))); // NOI18N
        btnView.setText("Start");
        btnView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnAdvide.setBackground(new java.awt.Color(255, 255, 204));
        btnAdvide.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnAdvide.setForeground(new java.awt.Color(255, 204, 102));
        btnAdvide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hihihi.png"))); // NOI18N
        btnAdvide.setText("Coach Advide");
        btnAdvide.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdvide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvideActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setText("User ID");

        txtUserID.setBackground(new java.awt.Color(255, 255, 255));
        txtUserID.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtUserID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 206, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnAdvide, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewCE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewTE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewBMI)))
                        .addGap(18, 18, 18)
                        .addComponent(liquidProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(liquidProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 7, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewBMI, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewTE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewCE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdvide, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/weightlifting.png"))); // NOI18N
        jLabel4.setText("USER TRAINING");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel6.setText("Training Date");

        viewDate.setEditable(false);
        viewDate.setBackground(new java.awt.Color(255, 255, 255));
        viewDate.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        viewDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        viewEX1.setEditable(false);
        viewEX1.setBackground(new java.awt.Color(255, 255, 255));
        viewEX1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        viewEX1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        viewEX2.setEditable(false);
        viewEX2.setBackground(new java.awt.Color(255, 255, 255));
        viewEX2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        viewEX2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jStatusEX1.setBackground(new java.awt.Color(255, 255, 255));
        jStatusEX1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jStatusEX1.setText("Exercise 1");

        jStatusEX2.setBackground(new java.awt.Color(255, 255, 255));
        jStatusEX2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jStatusEX2.setText("Exercise 2");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ta.png"))); // NOI18N

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/treadmill.png"))); // NOI18N

        btnTrain.setBackground(new java.awt.Color(153, 204, 255));
        btnTrain.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnTrain.setForeground(new java.awt.Color(0, 153, 255));
        btnTrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/power.png"))); // NOI18N
        btnTrain.setText("Train");
        btnTrain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrainActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lotus.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStatusEX1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStatusEX2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewEX1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(viewEX2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewDate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewEX1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStatusEX1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jStatusEX2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewEX2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtAdvide.setBackground(new java.awt.Color(255, 255, 255));
        txtAdvide.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtAdvide.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel15.setText("Name");

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel16.setText("Level");

        viewName.setEditable(false);
        viewName.setBackground(new java.awt.Color(255, 255, 255));
        viewName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        viewName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        viewLevel.setEditable(false);
        viewLevel.setBackground(new java.awt.Color(255, 255, 255));
        viewLevel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        viewLevel.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel17.setText("Phone");

        viewphonr.setEditable(false);
        viewphonr.setBackground(new java.awt.Color(255, 255, 255));
        viewphonr.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        viewphonr.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jLabel18.setText("INFORMATION");

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel19.setText("Course ID");

        txtCourseID.setBackground(new java.awt.Color(255, 255, 255));
        txtCourseID.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtCourseID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAdvide)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewName)
                            .addComponent(viewLevel)
                            .addComponent(viewphonr)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCourseID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewphonr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(txtAdvide, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private boolean validateCourseID(String CourseID) {
        if (CourseID.isEmpty()) {
            showError("Course ID can't be empty!");
            txtCourseID.setText("");
            return false;
        }
        if (!CourseID.matches(View.COURSE_REGEX)) {
            showError("Invalid Course ID! Please Enter ID Follow Format COR-dddd");
            txtCourseID.setText("");
            return false;
        }
        return true;
    }

    private boolean validateUserID(String UserID) {
        if (UserID.isEmpty()) {
            showError("User ID can't be empty!");
            txtCourseID.setText("");
            return false;
        }
        if (!UserID.matches(View.USER_REGEX)) {
            showError("Invalid User ID! Please Enter ID Follow Format CUS-dddd");
            txtCourseID.setText("");
            return false;
        }
        return true;
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void updateProgressDisplay(Progress userProgress) {
        int totalExercises = progressService.countTotalExercises(userProgress.getExercisesStatusList());
        int completedExercises = progressService.countCompletedExercises(userProgress.getExercisesStatusList());
        int progressPercentage = (int) progressService.calculateProgressPercentage(totalExercises, completedExercises);
        double bmi = new UserService().findByID(userProgress.getUserID()).calBMI();
        String name = new UserService().findByID(userProgress.getUserID()).getName();
        String phone = new UserService().findByID(userProgress.getUserID()).getPhoneNumber();
        Boolean level = new ScheduleService().findScheduleByUserID(userProgress.getUserID()).getLevel();
        liquidProgress.setValue(progressPercentage);
        liquidProgress.setString(progressPercentage + "%");
        viewBMI.setText(String.format("%.2f", bmi));
        viewName.setText(name);
        viewphonr.setText(phone);
        viewLevel.setText(level ? "Beginner" : "Advaned");
        viewTE.setText(String.valueOf(totalExercises));
        viewCE.setText(String.valueOf(completedExercises));
    }

    public Progress getUserProgress(String userID, String courseID) {
        return progressService.getUserProgress(userID, courseID);
    }

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        String courseID = txtCourseID.getText().trim();
        String userID = txtUserID.getText().trim();

        if (!validateCourseID(courseID)) {
            return;
        }
        if (!validateUserID(userID)) {
            return;
        }
        Progress userProgress = getUserProgress(userID, courseID);
        updateProgressDisplay(userProgress);
        displaySession(userProgress);
    }//GEN-LAST:event_btnViewActionPerformed

    public boolean displaySession(Progress userProgress) {
        List<ExercisesStatus> exercisesStatusList = userProgress.getExercisesStatusList();
        List<LocalDate> sessionDates = userProgress.getSessionDates();

        for (int i = 0; i < sessionDates.size(); i++) {
            if (progressService.isSessionIncomplete(exercisesStatusList.get(i))) {
                setViewFields(sessionDates.get(i), exercisesStatusList.get(i));
                return true;
            }
        }
        return false;
    }

//    private void setViewFields(LocalDate date, ExercisesStatus exercisesStatus) {
//        viewDate.setText(date.format(DATE_FORMAT));
//        List<String> exercises = exercisesStatus.getListExercise();
//        Map<String, Boolean> statusMap = exercisesStatus.getExerciseStatusMap();
//
//        JTextField[] exerciseViews = {viewEX1, viewEX2};
//        JRadioButton[] statusCheckboxes = {jStatusEX1, jStatusEX2};
//
//        for (int i = 0; i < exerciseViews.length; i++) {
//            if (i < exercises.size()) {
//                String exercise = exercises.get(i);
//                exerciseViews[i].setText(exercise);
//                statusCheckboxes[i].setSelected(statusMap.getOrDefault(exercise, false));
//            } else {
//                exerciseViews[i].setText("");
//                statusCheckboxes[i].setSelected(false);
//            }
//        }
//    }
    private void setViewFields(LocalDate date, ExercisesStatus exercisesStatus) {
        viewDate.setText(date.format(DATE_FORMAT));
        List<String> exercises = exercisesStatus.getListExercise();

        JTextField[] exerciseViews = {viewEX1, viewEX2};

        for (int i = 0; i < exerciseViews.length; i++) {
            if (i < exercises.size()) {
                String exercise = exercises.get(i);
                exerciseViews[i].setText(exercise);
            } else {
                exerciseViews[i].setText("");
            }
        }
    }

    private void btnTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrainActionPerformed
        String courseID = txtCourseID.getText().trim();
        String userID = txtUserID.getText().trim();

        if (!validateCourseID(courseID)) {
            return;
        }
        if (!validateUserID(userID)) {
            return;
        }
        Progress userProgress = getUserProgress(userID, courseID);
        if (!displaySession(userProgress)) {
            JOptionPane.showMessageDialog(null, "Congratulations All sessions are complete!", "Notice", JOptionPane.INFORMATION_MESSAGE);
        } else {
            updateStatusForSession(userProgress);
            JOptionPane.showMessageDialog(null, "Session status updated!", "Notice", JOptionPane.INFORMATION_MESSAGE);
        }
        clearDisplay();
    }//GEN-LAST:event_btnTrainActionPerformed

    private void btnAdvideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvideActionPerformed
        if (!txtAdvide.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Your Advide has send for user!", "Notice", JOptionPane.INFORMATION_MESSAGE);
            txtAdvide.setText("");
        } else {
            showError("Advide can't be empty!");
        }
    }//GEN-LAST:event_btnAdvideActionPerformed

    public void updateStatusForSession(Progress userProgress) {
        List<ExercisesStatus> exercisesStatusList = userProgress.getExercisesStatusList();

        for (ExercisesStatus statusToUpdate : exercisesStatusList) {
            if (progressService.isSessionIncomplete(statusToUpdate)) {
                Map<String, Boolean> statusMap = statusToUpdate.getExerciseStatusMap();
                List<String> exercises = statusToUpdate.getListExercise();

                for (int i = 0; i < exercises.size(); i++) {
                    String exercise = exercises.get(i);
                    boolean newStatus = (i == 0) ? jStatusEX1.isSelected() : jStatusEX2.isSelected();
                    updateExerciseStatus(statusMap, exercise, newStatus);
                }
                break;
            }
        }

        for (int i = 0; i < progresses.size(); i++) {
            if (progresses.get(i).getUserID().equals(userProgress.getUserID())) {
                progresses.set(i, userProgress);
                break;
            }
        }

        new ProgressRepository().writeFile(progresses);
    }

    public void updateExerciseStatus(Map<String, Boolean> statusMap, String exercise, boolean newStatus) {
        statusMap.put(exercise, newStatus);
    }

    public void clearDisplay() {
        txtCourseID.setText("");
        txtUserID.setText("");
        viewDate.setText("");
        viewBMI.setText("");
        viewName.setText("");
        viewLevel.setText("");
        viewphonr.setText("");
        viewEX1.setText("");
        viewEX2.setText("");
        liquidProgress.setValue(40);
        liquidProgress.setString("40%");
        viewTE.setText("");
        viewCE.setText("");
        txtUserID.setText("");
        jStatusEX1.setSelected(false);
        jStatusEX2.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoachTranning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoachTranning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoachTranning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoachTranning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoachTranning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdvide;
    private javax.swing.JButton btnTrain;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jStatusEX1;
    private javax.swing.JRadioButton jStatusEX2;
    private progressSwing.LiquidProgress liquidProgress;
    private javax.swing.JTextField txtAdvide;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField viewBMI;
    private javax.swing.JTextField viewCE;
    private javax.swing.JTextField viewDate;
    private javax.swing.JTextField viewEX1;
    private javax.swing.JTextField viewEX2;
    private javax.swing.JTextField viewLevel;
    private javax.swing.JTextField viewName;
    private javax.swing.JTextField viewTE;
    private javax.swing.JTextField viewphonr;
    // End of variables declaration//GEN-END:variables
}
